homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    methods: [POST, GET]

profilc:
    path:    /profilc
    defaults: { _controller: AppBundle:Default:profilc }
    methods: [POST, GET]
